### ISSUE TITLE
Error in installation of library

### ISSUE THREAD

**Issue by nsniteshsahni** [mPAND/gnp#2]
Hi there,
I have tried installing your library by the command `pip install gnp` and got the following error each and every time:

> Collecting gnp
>   Using cached gnp-0.0.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Nitesh\AppData\Local\Temp\pip-build-es045ufd\gnp\setup.py", line 6, in <module>
>         long_description = file.read()
>       File "c:\users\nitesh\appdata\local\programs\python\python35\lib\encodings\cp1252.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4894: character maps to <undefined>
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\Nitesh\AppData\Local\Temp\pip-build-es045ufd\gnp\ 

Hoping a issue resolution
Thank you in advance

**Comment by kamaleshvm** [comment]
I'm also facing the same issue mentioned

**Comment by thleo** [comment]
Have there been any updates to the library in 2017? Also having this issue.  Updating setuptools didn't help
